/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eloyvscifpaviles.aeropuerto_eloyvecino;

import com.eloyvscifpaviles.gui.dlgMenuCompanya;
import com.eloyvscifpaviles.gui.dlgMenuPaneles;
import com.eloyvscifpaviles.gui.dlgMenuVueloBase;
import com.eloyvscifpaviles.gui.dlgMenuVueloDiario;
import com.eloyvscifpaviles.logica.LogicaNegocio;

/**
 *
 * @author eloyv
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCompanya = new javax.swing.JButton();
        btnVuelosB = new javax.swing.JButton();
        btnVuelosD = new javax.swing.JButton();
        btnPaneles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCompanya.setText("Compañías");
        btnCompanya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyaActionPerformed(evt);
            }
        });

        btnVuelosB.setText("Vuelos Base");
        btnVuelosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelosBActionPerformed(evt);
            }
        });

        btnVuelosD.setText("Vuelos Diarios");
        btnVuelosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelosDActionPerformed(evt);
            }
        });

        btnPaneles.setText("Paneles");
        btnPaneles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnCompanya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVuelosB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnVuelosD)
                        .addGap(75, 75, 75)
                        .addComponent(btnPaneles)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompanya)
                    .addComponent(btnVuelosB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVuelosD)
                    .addComponent(btnPaneles))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompanyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyaActionPerformed
        dlgMenuCompanya menuCompanya = new dlgMenuCompanya();
        menuCompanya.setVisible(true);
    }//GEN-LAST:event_btnCompanyaActionPerformed

    private void btnVuelosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelosDActionPerformed
        dlgMenuVueloDiario menuVueloD = new dlgMenuVueloDiario();
        menuVueloD.setVisible(true);
    }//GEN-LAST:event_btnVuelosDActionPerformed

    private void btnVuelosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelosBActionPerformed
        dlgMenuVueloBase menuVueloB = new dlgMenuVueloBase();
        menuVueloB.setVisible(true);
    }//GEN-LAST:event_btnVuelosBActionPerformed

    private void btnPanelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelesActionPerformed
        dlgMenuPaneles menuPaneles = new dlgMenuPaneles();
        menuPaneles.setVisible(true);
    }//GEN-LAST:event_btnPanelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         LogicaNegocio.inicializarAeropuertos();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompanya;
    private javax.swing.JButton btnPaneles;
    private javax.swing.JButton btnVuelosB;
    private javax.swing.JButton btnVuelosD;
    // End of variables declaration//GEN-END:variables
}
